### PR TITLE
Update 2015-11-08-tracking.md

### PR DESCRIPTION
**Pull request by gaede**
Added last names, so people know who are the organizers.

### CODE REVIEW

**Comment by hegner** [comment]
Hi Frank, 
for next time do it on https://github.com/HEP-SF/hep-sf.github.io directly. 
This one I'll push upstream.

**Comment by gaede** [comment]
Hi Benedikt,
I tried to do it in https://github.com/HEP-SF/hep-sf.github.io, however github told me that I have no write access and created a fork and then I simply followed the procedure suggested by github.
Just wanted to see what happens and how intuitive the system is...
Btw. the change is still not online - is it ?

**Comment by hegner** [comment]
Now it should be. You made the pull request to my private repository, not the official one. Thus I had to forward ;-)

**Comment by gaede** [comment]
arghh - I know why I prefer svn over git ;-)
> On 12 Nov 2015, at 13:35, hegner <notifications@github.com> wrote:
> 
> Now it should be. You made the pull request to my private repository, not the official one. Thus I had to forward ;-)
> 
> —
> Reply to this email directly or view it on GitHub.
> 

------------------------------------ 
Dr. Frank Gaede
DESY - FLC
 Phone:  +49 40 8998 4382    
 Fax:    +49 40 8994 4382
 E-mail: frank.gaede@desy.de

**Comment by jouvin** [comment]
@gaede you'll soon change your mind! The "permission problem" you have seen is normal: this is the normal way of doing it. We discussed this offline with Benedikt and Torre, we clearly need to document it in more details...

**Pull request merged**
